version: '3.9'

services:

  db:
    image: postgres:13.6
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: andrei
      POSTGRES_DB: digital_catalog
    restart: on-failure
    healthcheck:
      test: "psql -U andrei -d digital_catalog -c 'select 1;'"
      interval: 1s
      retries: 20
    volumes:
      - database_digital_catalog_dev:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - digital_catalog_dev
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: foo@bar.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      - "1337:80"

    volumes:
      - database_digital_catalog_pgadmin:/var/lib/pgadmin
    networks:
      - digital_catalog_dev

volumes:
  database_digital_catalog_dev:
  database_digital_catalog_pgadmin:

networks:
  digital_catalog_dev: